"""Document Search — Level 3 (open-ended analysis with LLM judge).

Questions require synthesis and strategic analysis — no single correct answer:
  - "What does Company X's growth trajectory suggest about its strategy?"
  - "Compare the founding periods and industries of Companies A, B, and C."
  - "Which of these companies appears best positioned for long-term growth?"

Reward: vf.JudgeRubric — gpt-4.1 as judge evaluating quality of analysis.
Ground truth: short reference answers generated by GPT-4.1 at build time.

Requires: OPENAI_API_KEY in environment for judge calls.
Starting reward with 1B model: ~0.20-0.40.
Ceiling is ~0.75-0.85 (judge rarely awards perfect scores).

This level demonstrates:
  - LLM-as-judge reward (when programmatic reward is impossible)
  - Open-ended response evaluation
  - How to combine tool-retrieved facts with qualitative reasoning
"""
from __future__ import annotations

import random
import verifiers as vf
from datasets import Dataset

from lab_cookbook.skills.lab.dataset_builder import DatasetBuilder
from lab_cookbook.recipes.document_search import document_search_l1 as l1

SYSTEM_PROMPT = """You are a senior business analyst with access to a company database.
Use search_docs and get_metadata to gather the facts you need, then write a thoughtful analysis.

Your response should:
- Be grounded in the actual data you retrieve from the database
- Provide specific numbers and comparisons
- Draw clear conclusions
- Be 2-4 sentences (concise but substantive)
"""

# Reference answers (ground truth for judge)
# These are short reference analyses that the judge uses as rubric guidance.

def _build_qa_pairs(corpus: dict, n: int = 200, seed: int = 42) -> Dataset:
    """Build open-ended analysis questions over the corpus."""
    rng = random.Random(seed)
    builder = DatasetBuilder()
    docs = list(corpus.values())

    templates = [
        # (question_fn, reference_answer_fn)
        (
            lambda d: (
                f"What does {d['name']}'s founding year of {d['founded']} "
                f"and current size of {d['employees']} employees suggest about its growth trajectory?"
            ),
            lambda d: (
                f"{d['name']} was founded in {d['founded']} in the {d['industry']} industry. "
                f"With {d['employees']} employees, it has {'grown substantially' if d['employees'] >= 1000 else 'remained a focused operation'}. "
                f"A {'long-established' if d['founded'] < 2000 else 'relatively young'} company "
                f"{'generating $' + str(d['revenue_millions']) + 'M in revenue suggests strong unit economics.' if d['revenue_millions'] >= 100 else 'at this stage is still scaling its revenue model.'}"
            ),
        ),
        (
            lambda pair: (
                f"Compare {pair[0]['name']} and {pair[1]['name']} in terms of their "
                f"founding era, industry, and scale."
            ),
            lambda pair: (
                f"{pair[0]['name']} ({pair[0]['industry']}, founded {pair[0]['founded']}, "
                f"{pair[0]['employees']} employees, ${pair[0]['revenue_millions']}M revenue) vs "
                f"{pair[1]['name']} ({pair[1]['industry']}, founded {pair[1]['founded']}, "
                f"{pair[1]['employees']} employees, ${pair[1]['revenue_millions']}M revenue). "
                f"{'Both operate in the same industry, making them direct peers.' if pair[0]['industry'] == pair[1]['industry'] else 'They operate in different industries, limiting direct comparison.'}"
            ),
        ),
        (
            lambda trio: (
                f"Of {trio[0]['name']}, {trio[1]['name']}, and {trio[2]['name']}, "
                f"which appears best positioned for long-term growth and why?"
            ),
            lambda trio: (
                f"Based on revenue per employee and founding era: "
                f"{max(trio, key=lambda d: d['revenue_millions'] / max(d['employees'], 1))['name']} "
                f"has the best revenue-per-employee ratio, suggesting operational efficiency. "
                f"All three are established {trio[0]['industry'] if all(d['industry'] == trio[0]['industry'] for d in trio) else 'companies across different industries'}."
            ),
        ),
    ]

    for _ in range(n):
        template_idx = rng.randint(0, len(templates) - 1)
        q_fn, a_fn = templates[template_idx]

        if template_idx == 0:
            subject = rng.choice(docs)
            question = q_fn(subject)
            reference = a_fn(subject)
        elif template_idx == 1:
            pair = rng.sample(docs, 2)
            question = q_fn(pair)
            reference = a_fn(pair)
        else:
            trio = rng.sample(docs, 3)
            question = q_fn(trio)
            reference = a_fn(trio)

        builder.add(question, reference)

    return builder.build()


# Judge rubric criteria

JUDGE_CRITERIA = """Given a question, a reference answer, and a response, decide whether the response is correct.

Question:
```
{question}
```

Reference answer:
```
{answer}
```

Response:
```
{response}
```

Evaluation criteria:
1. factual accuracy,
2. groundedness,
3. analytical quality,
4. conciseness.

Reply with only "yes" or "no".
"""


# load_environment

def load_environment(
    num_examples: int = -1,
    seed: int = 42,
) -> vf.Environment:
    """Load Document Search L3 environment.

    Requires OPENAI_API_KEY for the LLM judge.

    Args:
        num_examples: Number of examples to use (-1 = all ~200).
        seed: Random seed.

    Returns:
        ToolEnv with JudgeRubric for open-ended analysis questions.
    """
    l1._ensure_corpus_loaded(seed=seed)
    dataset = _build_qa_pairs(l1._CORPUS, seed=seed)
    if num_examples != -1:
        dataset = dataset.select(range(min(num_examples, len(dataset))))

    rubric = vf.JudgeRubric(
        judge_model="gpt-4.1",
        judge_prompt=JUDGE_CRITERIA,
    )

    return vf.ToolEnv(
        dataset=dataset,
        system_prompt=SYSTEM_PROMPT,
        tools=[l1.search_docs, l1.get_metadata],
        rubric=rubric,
    )


if __name__ == "__main__":
    l1._ensure_corpus_loaded()
    env = load_environment(num_examples=5)
    print(f"Dataset size: {len(env.dataset)}")
    for row in env.dataset.select(range(3)):
        print(f"  Q: {row['question'][:100]}...")
        print(f"  Reference: {row['answer'][:100]}...")
        print()
