model = "openai/gpt-oss-20b:my-sft-lora-distilled-from-oss-120b-distill"

[teacher]
model = "openai/gpt-oss-120b"
teacher_tau = 0.5

[sampling]
max_tokens = 512
reasoning_effort = "medium"

[[env]]
id = "prime/wordle"
